
/* IMPORT */

const DEFAULT_RETRIES = 1;
const DEFAULT_RETRY_INTERVAL = 10;
const DEFAULT_STALE_INTERVAL = 10_000;
const DEFAULT_UPDATE_FREQUENCY = .1;

/* EXPORT */

export {DEFAULT_RETRIES, DEFAULT_RETRY_INTERVAL, DEFAULT_STALE_INTERVAL, DEFAULT_UPDATE_FREQUENCY};
